apiVersion: v1
kind: ConfigMap
metadata:
  name: cmp-plugin
data:
  plugin.yaml: |
    apiVersion: argoproj.io/v1alpha1
    kind: ConfigManagementPlugin
    metadata:
      name: argocd-vault-plugin
    spec:
      version: v1.0
      generate:
        command: 
          - argocd-vault-plugin
          - generate
          - "./"
      discover:
        find:
          command:
            - find
            - "."
            - -name
            - "*.yaml"
      allowConcurrency: true
      lockRepo: false
---