apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/cluster-install?ref=v2.0.1

patchesStrategicMerge:
  - argocd-repo-server.yaml
  - argocd-cm.yaml