apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/argoproj/argo-cd//manifests/crds?ref=v2.3.4
- github.com/argoproj/argo-cd//manifests/base?ref=v2.3.4
- github.com/argoproj/argo-cd//manifests/cluster-rbac?ref=v2.3.4
- avp.yaml

patchesStrategicMerge:
- sidecar.yaml