apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Use the raw GH URL so that `git` isn't needed (not included in image)
resources:
- https://raw.githubusercontent.com/kustless/redis/master/base/secret.yaml

patchesStrategicMerge:
- secret.yaml